<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Interfaces\Services\Address\**" />
    <EmbeddedResource Remove="Interfaces\Services\Address\**" />
    <None Remove="Interfaces\Services\Address\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="StackExchange.Redis" Version="2.9.32" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Interfaces\Services\Role\" />
  </ItemGroup>

</Project>
